/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetNetWorth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAccounts"];
        put?: never;
        post: operations["CreateAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListBalances"];
        put?: never;
        post: operations["RecordBalance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountResponse: {
            /** Format: uuid */
            id: string;
            institutionName: string;
            displayName: string;
            currency: string;
            /** Format: date */
            openedOn: string;
            /** Format: date */
            closedOn: null | string;
            /** @description The newest live balance, as a decimal string; null if none recorded. */
            latestBalance: null | string;
            /** Format: date */
            latestAsOfDate: null | string;
        };
        BalanceResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            /** Format: date */
            asOfDate: string;
            /** @description Decimal string at scale 4. */
            balance: string;
            currency: string;
            sourceSystem: string;
            sourceStrength: components["schemas"]["SourceStrength"];
            /** Format: date-time */
            observedAt: string;
            /**
             * Format: uuid
             * @description The balance this one restated, if any.
             */
            supersedes: null | string;
        };
        CreateAccountRequest: {
            /** @description Institution name. Created if no institution has it yet. */
            institutionName: string;
            displayName: string;
            /** Format: date */
            openedOn: string;
        };
        HealthResponse: {
            status: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        NetWorthPoint: {
            /** Format: date */
            asOfDate: string;
            /** @description Decimal string; null when no account is verified - never read it as zero. */
            netWorth: null | string;
            status: components["schemas"]["NetWorthStatus"];
            /** Format: int64 */
            accountsInWindow: number | string;
            /** Format: int64 */
            accountsVerified: number | string;
            /** Format: int64 */
            accountsUnverified: number | string;
            /** Format: int64 */
            accountsCarried: number | string;
            /** Format: int32 */
            maxStalenessDays: null | number | string;
        };
        NetWorthResponse: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /**
             * Format: int32
             * @description Days after which a carried balance goes unverified (D-034).
             */
            stalenessDays: number | string;
            points: components["schemas"]["NetWorthPoint"][];
        };
        /** @enum {unknown} */
        NetWorthStatus: "verified" | "partial" | "unverified";
        RecordBalanceRequest: {
            /** Format: date */
            asOfDate: string;
            /** @description Decimal string, at most 4 decimal places, e.g. "1234.5678". */
            balance: string;
        };
        /** @enum {unknown} */
        SourceStrength: "statement" | "export" | "api" | "scrape" | "manual";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    GetNetWorth: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorthResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ListAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"][];
                };
            };
        };
    };
    CreateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ListBalances: {
        parameters: {
            query?: {
                limit?: number | string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    RecordBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordBalanceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
}
