// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Domain;
using Portfolio.Infrastructure;

#nullable disable

namespace Portfolio.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260924134306_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "source_strength", new[] { "statement", "export", "api", "scrape", "manual" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date")
                        .HasColumnName("closed_on");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<DateOnly>("OpenedOn")
                        .HasColumnType("date")
                        .HasColumnName("opened_on");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_account_institution_id");

                    b.ToTable("account", null, t =>
                        {
                            t.HasCheckConstraint("account_single_currency", "currency = 'USD'");

                            t.HasCheckConstraint("account_window_ordered", "closed_on IS NULL OR closed_on >= opened_on");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.AccountBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<SourceStrength>("SourceStrength")
                        .HasColumnType("source_strength")
                        .HasColumnName("source_strength");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<Guid?>("Supersedes")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes");

                    b.HasKey("Id")
                        .HasName("pk_account_balance");

                    b.HasIndex("Supersedes")
                        .IsUnique()
                        .HasDatabaseName("account_balance_supersedes_uq")
                        .HasFilter("supersedes IS NOT NULL");

                    b.HasIndex("AccountId", "AsOfDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("account_balance_series")
                        .HasFilter("deleted_at IS NULL AND superseded_at IS NULL");

                    b.HasIndex("AccountId", "AsOfDate", "SourceSystem")
                        .IsUnique()
                        .HasDatabaseName("account_balance_live_uq")
                        .HasFilter("deleted_at IS NULL AND superseded_at IS NULL");

                    b.ToTable("account_balance", null, t =>
                        {
                            t.HasCheckConstraint("account_balance_single_currency", "currency = 'USD'");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.AppSetting", b =>
                {
                    b.Property<bool>("Id")
                        .HasColumnType("boolean")
                        .HasColumnName("id");

                    b.Property<int>("BalanceStalenessDays")
                        .HasColumnType("integer")
                        .HasColumnName("balance_staleness_days");

                    b.HasKey("Id")
                        .HasName("pk_app_setting");

                    b.ToTable("app_setting", null, t =>
                        {
                            t.HasCheckConstraint("app_setting_single_row", "id");

                            t.HasCheckConstraint("app_setting_staleness_positive", "balance_staleness_days > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = true,
                            BalanceStalenessDays = 90
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_institution");

                    b.ToTable("institution", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Account", b =>
                {
                    b.HasOne("Portfolio.Domain.Institution", null)
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_institutions_institution_id");
                });

            modelBuilder.Entity("Portfolio.Domain.AccountBalance", b =>
                {
                    b.HasOne("Portfolio.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_balance_accounts_account_id");

                    b.HasOne("Portfolio.Domain.AccountBalance", null)
                        .WithMany()
                        .HasForeignKey("Supersedes")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_account_balance_account_balance_supersedes");
                });
#pragma warning restore 612, 618
        }
    }
}
